version: '1'

services:
  postgres:
    image: postgres:15.1
    domainname: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=geekmarket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
