server:
  port: 8080
  servlet:
    context-path: /market
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/geekmarket
    username: postgres
    password: postgres
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

jwt:
  secret: fasdfo3451kb12l3k4h12k5h2lkj5h12lk3b5l12kg61l2k451lk15l43k5h1
  lifetime: 36000000



#server.port=8080
#server.servlet.context-path=/market
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5433/geekmarket
#
#
#spring.liquibase.change-log=classpath*:db/changelog/changelog-master.xml
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true