server:
  port: 8090
  servlet:
    context-path: /market-carts
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/geekmarket
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  graphql:
    cors:
      allow-credentials: true

integrations:
  services:
    products-url: http://localhost:9000/market-products/api/v1
    auth-url: http://localhost:6000/market-auth/api/v1
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

jwt:
  secret: fasdfo3451kb12l3k4h12k5h2lkj5h12lk3b5l12kg61l2k451lk15l43k5h1

cart-service:
  cart-prefix: market_cart_


